# Generated by Django 4.1 on 2023-01-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optional_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='field',
            new_name='fields',
        ),
    ]
