# Generated by Django 4.1 on 2023-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optional_courses', '0002_rename_field_course_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['username']},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_full_name'),
        ),
    ]
