# Generated by Django 4.1 on 2023-01-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optional_courses', '0003_alter_student_options_student_unique_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='optional_courses.universitygroup'),
        ),
    ]
